pub const PFCP_HEARTBEAT_REQUEST: u8                = 1;
pub const PFCP_HEARTBEAT_RESPONSE: u8               = 2;
pub const PFCP_PFD_MANAGEMENT_REQUEST: u8           = 3;
pub const PFCP_PFD_MANAGEMENT_RESPONSE: u8          = 4;
pub const PFCP_ASSOCIATION_SETUP_REQUEST: u8        = 5;
pub const PFCP_ASSOCIATION_SETUP_RESPONSE: u8       = 6;
pub const PFCP_ASSOCIATION_UPDATE_REQUEST: u8       = 7;
pub const PFCP_ASSOCIATION_UPDATE_RESPONSE: u8      = 8;
pub const PFCP_ASSOCIATION_RELEASE_REQUEST: u8      = 9;
pub const PFCP_ASSOCIATION_RELEASE_RESPONSE: u8     = 10;
pub const PFCP_VERSION_NOT_SUPPORTED_RESPONSE: u8   = 11;
pub const PFCP_NODE_REPORT_REQUEST: u8              = 12;
pub const PFCP_NODE_REPORT_RESPONSE: u8             = 13;
pub const PFCP_SESSION_SET_DELETION_REQUEST: u8     = 14;
pub const PFCP_SESSION_SET_DELETION_RESPONSE: u8    = 15;
pub const PFCP_SESSION_SET_MODIFICATION_REQUEST: u8 = 16;
pub const PFCP_SESSION_SET_MODIFCATION_RESPONSE: u8 = 17;


pub const PFCP_SESSION_ESTABLISHMENT_REQUEST: u8    = 50;
pub const PFCP_SESSION_ESTABLISHMENT_RESPONSE: u8   = 51;
pub const PFCP_SESSION_MODIFICATION_REQUEST: u8     = 52;
pub const PFCP_SESSION_MODIFICATION_RESPONSE: u8    = 53;
pub const PFCP_SESSION_DELETION_REQUEST: u8         = 54;
pub const PFCP_SESSION_DELETION_RESPONSE: u8        = 55;
pub const PFCP_SESSION_REPORT_REQUEST: u8           = 56;
pub const PFCP_SESSION_REPORT_RESPONSE: u8          = 57;
